apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "binance-daemon.fullname" . }}-scripts
data:

  recover.sh: |
    #!/bin/bash

    FILE=/opt/bnbchaind/.probe_last_height
    [ ! -f "$FILE" ] && exit 0

    HEIGHT=$(($(cat $FILE) - 1))
    if [ "$HEIGHT" -gt "1" ]; then
      su bnbchaind -c "/release/linux/state_recover $HEIGHT /opt/bnbchaind"
    fi

    # some envs inject a security context that can cause permission issues after recover
    chown -R bnbchaind:bnbchaind /opt/bnbchaind

  probe.sh: |
    #!/bin/bash

    FILE=/opt/bnbchaind/.probe_last_height
    ENDPOINT=localhost:$BINANCE_DAEMON_SERVICE_PORT_RPC/status

    STATUS=$(curl -sL --fail -m 10 "$ENDPOINT") || exit 1
    if [ ! -f "$FILE" ]; then
      echo "$STATUS" | jq -r ".result.sync_info.index_height" >$FILE
      exit 1
    fi

    PULLING_SNAPSHOT=$(echo "$STATUS" | jq '.result.sync_info.index_height == "0"')
    [[ "$PULLING_SNAPSHOT" == "true" ]] && exit 0

    OLD=$(cat $FILE)
    echo "$STATUS" | jq -r ".result.sync_info.index_height" >$FILE
    CURRENT=$(cat $FILE)
    [ "$OLD" == "$CURRENT" ] && exit 1

    # reset snapshots if probe found a height
    if grep -q 'state_sync_reactor = true' /opt/bnbchaind/config/config.toml; then
      exit 1
    fi

  entrypoint.sh: |
    #!/bin/bash

    set -ex

    BNET=${BNET:-mainnet}
    EXE="ulimit -n 65535 && /release/linux/bnbchaind start --home ${BNCHOME}"
    PROBE=/opt/bnbchaind/.probe_last_height

    # initialize config
    if [ ! -d "${BNCHOME}/config/" ]; then
      mkdir -p "${BNCHOME}/config/"
    fi
    cp "/release/${BNET}/config.toml" "${BNCHOME}/config/"
    cp "/release/${BNET}/app.toml" "${BNCHOME}/config/"
    cp "/release/${BNET}/genesis.json" "${BNCHOME}/config/"
    chown -R bnbchaind:bnbchaind "${BNCHOME}/config/"

    # turn on console logging
    sed -i 's/logToConsole = false/logToConsole = true/g' "${BNCHOME}/config/app.toml"

    # enable telemetry
    sed -i "s/prometheus = false/prometheus = true/g" "${BNCHOME}/config/config.toml"
    sed -i -e "s/prometheus_listen_addr = \":26660\"/prometheus_listen_addr = \":28660\"/g" "${BNCHOME}/config/config.toml"

    # disable snapshots and clear if already recovered
    if [ -f "$PROBE" ] && [ $(cat "$PROBE") -gt "0" ]; then
      rm -rf /opt/bnbchaind/data/snapshot
      rm -rf /opt/bnbchaind/snapshots
      sed -i "s/state_sync_reactor = true/state_sync_reactor = false/g" "${BNCHOME}/config/config.toml"
    fi

    # reduce log noise
    sed -i "s/consensus:info/consensus:error/g" "${BNCHOME}/config/config.toml"
    sed -i "s/dexkeeper:info/dexkeeper:error/g" "${BNCHOME}/config/config.toml"
    sed -i "s/dex:info/dex:error/g" "${BNCHOME}/config/config.toml"
    sed -i "s/state:info/state:error/g" "${BNCHOME}/config/config.toml"

    su bnbchaind -c "$EXE"
