apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "avalanche-daemon.fullname" . }}-chain-configs
data:
  C-config.json: |
    {
      "state-sync-enabled": true,
      "eth-apis": [
        "public-eth",
        "public-eth-filter",
        "net",
        "web3",
        "internal-public-eth",
        "internal-public-blockchain",
        "internal-public-transaction-pool",
        "internal-public-account",
        "internal-public-tx-pool"
      ],
      "local-txs-enabled": true
    }
