---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mirror-backups
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
