{{- if .Values.mnemonic -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.mnemonicSecret | default "thornode-mnemonic" }}
type: Opaque
stringData:
  mnemonic: {{ .Values.mnemonic }}
{{- end -}}
